site_name: 'Backstage'
site_description: 'Main documentation for Backstage Bla Bla Bla'
repo_url: https://github.com/iamsureshgithub/backstage
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  #- redirects:
  #    redirect_maps:
  #      'index.md': 'docs/index.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - What is Bla Bla Bla?: 'docs/index.md'
